apiVersion: v2
name: fleetdm
description: Flamingo Home Assignment Helm chart for FleetDM server
version: 0.1.0
appVersion: "v4.64.0"
dependencies:
  - name: redis
    version: "25.3.7"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled