fleetdm:
  image:
    repository: fleetdm/fleet
    tag: v4.64.0
  replicas: 1
  serverAddress: "0.0.0.0:8080"
  redis:
    port: 6379
    database: "0"
    passwordSecretKey: redis-password
  service:
    type: ClusterIP
    port: 8080

mysql:
  image: mysql:8.0
  port: 3306
  database: fleet
  user: fleet
  password: ""

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: ""
    existingSecret: ""
