apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fleet
  labels:
    app: fleet
spec:
  replicas: {{ .Values.fleetdm.replicas }}
  selector:
    matchLabels:
      app: fleet
  template:
    metadata:
      labels:
        app: fleet
    spec:
      containers:
        - name: fleet
          image: {{ .Values.fleetdm.image.repository }}:{{ .Values.fleetdm.image.tag }}
          ports:
            - containerPort: {{ .Values.fleetdm.service.port }}
          env:
            - name: FLEET_SERVER_ADDRESS
              value: {{ .Values.fleetdm.serverAddress | quote }}
            - name: FLEET_MYSQL_ADDRESS
              value: "{{ .Release.Name }}-mysql:{{ .Values.mysql.port }}"
            - name: FLEET_MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
            - name: FLEET_MYSQL_USERNAME
              value: {{ .Values.mysql.user | quote }}
            - name: FLEET_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql
                  key: mysql-password
            - name: FLEET_REDIS_ADDRESS
              value: "{{ .Release.Name }}-redis-master:{{ .Values.fleetdm.redis.port }}"
            - name: FLEET_REDIS_DATABASE
              value: {{ .Values.fleetdm.redis.database | quote }}
            - name: FLEET_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: {{ .Values.fleetdm.redis.passwordSecretKey | quote }}
            - name: FLEET_SERVER_TLS
              value: "false"
            - name: FLEET_OSQUERY_ENABLE_TLS
              value: "false"
            - name: FLEET_INSECURE
              value: "true"